server:
  port: 9091
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 200
      min-spare: 10
spring:
  application:
    name: ratelimiter-demo
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    username: ratelimit
    password: password
    url: ${external.db-url}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 12

internal:
  allowed-request-period: "PT2S"

external:
  db-url: ${DB_URL:jdbc:postgresql://localhost:15432/test_db}
  loki-url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
  zipkin-url: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${external.zipkin-url}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true