server:
  port: 9091
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 200
      min-spare: 10
spring:
  application:
    name: ratelimiter-demo
  lifecycle:
    timeout-per-shutdown-phase: 30s # ?????, ? ??????? ???????? ??????? ??????? ????? ?????????????? ????? ????????? ??????? SIGTERM
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/test_db
    hikari:
      connection-timeout: 2000 # ? ?????????????
      maximum-pool-size: 12