version: "3.8"
services:
  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=test_db
      - PGUSER=${DB_USER}
    volumes:
      - ratelimiter:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "test_db", "-U", "ratelimiter_user" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  ratelimiter:
    driver: local