version: "3.8"
services:

  ratelimiter-service:
    image: "ratelimiter-demo"
    container_name: "ratelimiter-service"
    ports:
      - "9091:9091"
    environment:
      - LOKI_URL=${LOKI_URL}
      - DB_URL=${DB_URL}
      - ZIPKIN_URL=${ZIPKIN_URL}
    depends_on:
      postgres:
        condition: service_healthy

  ratelimiter-service-2:
    image: "ratelimiter-demo"
    container_name: "ratelimiter-service-2"
    ports:
      - "9095:9091"
    environment:
      - LOKI_URL=${LOKI_URL}
      - DB_URL=${DB_URL}
      - ZIPKIN_URL=${ZIPKIN_URL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    ports:
      - "15432:15432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=test_db
      - PGUSER=${DB_USER}
      - PGPORT=15432
    volumes:
      - ratelimiter:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ratelimit", "-d", "test_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  prometheus:
    image: "prom/prometheus:v2.51.2"
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana-oss:11.2.0"
    container_name: "grafana"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  tempo:
    image: grafana/tempo:2.4.2
    command: -config.file=/etc/tempo.yml
    container_name: tempo
    ports:
      - "3200:3200"   # tempo
      - "9411:9411"   # zipkin
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml

  loki:
    image: grafana/loki:main
    command: -config.file=/etc/loki/local-config.yaml
    container_name: loki
    ports:
      - "3100:3100"

volumes:
  ratelimiter:
    driver: local